### ISSUE TITLE
Output Tab is Blank

### ISSUE THREAD

**Issue by elijahpaul888** [reimund/Tych-Panel#14]
Whenever I click on the Output button, it shows a blank tab. Appearance and Misc tabs appear to be working. I ran ExtendScript Toolkit and this is what I got (if it helps):

![screen shot 2014-10-27 at 15 54 41](https://cloud.githubusercontent.com/assets/9418440/4792855/b1109850-5de9-11e4-9d03-6d09b743c00d.png)

I am using PS CC 2014 on Yosemite OSX

**Comment by reimund** [comment]
Please try 2.3.2 and see if you still get this problem. Closing for now.
