### ISSUE TITLE
Photoshop CC 2015 - not working

### ISSUE THREAD

**Issue by nicklucas** [reimund/Tych-Panel#17]
I've tried installing Tych Panel in the new Photoshop CC 2015 and, although it appears in the extension manager ok, the button in Photoshop don't do anything. There are no files in the presets/scripts folder for Photoshop CC 2015.

**Comment by nicklucas** [comment]
I've tried installing 2.3.3 today (24/6/2015) and it's still the same - the panel appears but the buttons do not do anything.

**Comment by reimund** [comment]
Yeah, waiting for Adobe to fix a bug in Creative Cloud...

/R

onsdag 24 juni 2015 skrev nicklucas <notifications@github.com>:

**Comment by mpc99** [comment]
Same issue here, I installed the latest version 2.3.4 and buttons are dead nothing happens in Photoshop CC2015. :~(

**Comment by Hobbledig** [comment]
I'm sorry that it's not working. I've reinstalled today and the buttons are dead. I also have CC 2015 :(
![tp1](https://cloud.githubusercontent.com/assets/13274598/8619589/930e89fc-275b-11e5-9d26-b537186b1682.JPG)
![tp2](https://cloud.githubusercontent.com/assets/13274598/8619590/9310e35a-275b-11e5-8547-0d70d2ace895.JPG)

**Comment by reimund** [comment]
Looks like the old options script is still running. You could try
installing manually. Look in the install log and copy the files yourself.

2015-07-10 15:30 GMT+02:00 Hobbledig <notifications@github.com>:

**Comment by RCP07** [comment]
Thanks Reimund but I already did that. I uninstalled then did a manual install by copying the files and when that didn't work I uninstalled the copied files and reinstalled via Extension Manager again just to make sure that I tried all options. Not having much luck, sorry.

**Comment by reimund** [comment]
What's the path of the extension and what is the path of the scripts?
Can you run the scripts from File > Script? What is the output?

/R

2015-07-10 16:00 GMT+02:00 RCP07 <notifications@github.com>:

**Comment by RCP07** [comment]
No I cannot run a script from File > Script. The script page comes up but cannot input color or border color and buttons titles not showing as per image above and clicking ok nothing happens

Sat Jul 11 2015 00:43:10 GMT+1000
 	Company: 
 	Product: Tych Panel
 	Product version: 2.3.4
 	App: photoshop
 	App Version: 16.0.0
 	OS: Windows 7/64 6.1 Service Pack 1 
 	Locale: en_US
 ---------------------------------------
 	Installer Version: 0.1.1
 =======================================

Preflight 
----------------------------
OK: PS version 16 in the range [0, 99]

Items to be installed 
----------------------------
- HTML_PANEL
- SCRIPT
- MAC_PLUGIN
- WIN_PLUGIN
- EXTRA


Adding HTML_PANEL
----------------------------
Destination folder: C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel
Destination Folder successfully created.

List of Folders to be copied for the HTML_PANEL:
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\html-panel\CSXS
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\html-panel\images
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\html-panel\js
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\html-panel\META-INF
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\html-panel\styles
Folder: ~/Documents/Tych%20Panel/CC%202015/assets/html-panel

Creating Folders in destination and copying files:

Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel
Copied:		Icon.png
Copied:		index.html
Copied:		mimetype
Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel\CSXS
Copied:		manifest.xml
Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel\images
Copied:		add-column-left.png
Copied:		add-column-right.png
Copied:		add-row-bottom.png
Copied:		add-row-top.png
Copied:		gear.png
Copied:		icon.png
Copied:		plus.png
Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel\js
Copied:		app.js
Copied:		CSInterface.js
Copied:		jquery.js
Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel\META-INF
Copied:		signatures.xml
Created Folder:	C:\Users\Rosa\AppData\Roaming\Adobe\CEP\extensions\Tych Panel\styles
Copied:		app.css

Ended copying files for HTML_PANEL.


Adding SCRIPT
----------------------------
Destination folder: C:\Program Files\Adobe\Adobe Photoshop CC 2015\Presets\Scripts\Tych Panel
Destination Folder successfully created.

List of Folders to be copied for the SCRIPT:
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\scripts\Images
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\scripts\Panel Helpers
Folder: C:\Users\Rosa\Documents\Tych Panel\CC 2015\assets\scripts\Tych Panel Only
Folder: ~/Documents/Tych%20Panel/CC%202015/assets/scripts

Creating Folders in destination and copying files:

Created Folder:	C:\Program Files\Adobe\Adobe Photoshop CC 2015\Presets\Scripts\Tych Panel
Copied:		Tych%20Panel%20-%20Options.jsx
Created Folder:	C:\Program Files\Adobe\Adobe Photoshop CC 2015\Presets\Scripts\Tych Panel\Images
Copied:		left-arrow.png
Copied:		reimund.jpg
Copied:		right-arrow.png
Copied:		thumbnail-unavailable.png
Created Folder:	C:\Program Files\Adobe\Adobe Photoshop CC 2015\Presets\Scripts\Tych Panel\Panel Helpers
Copied:		Tych%20Panel%20-%20New%20column%20(left).jsx
Copied:		Tych%20Panel%20-%20New%20column%20(right).jsx
Copied:		Tych%20Panel%20-%20New%20row%20(bottom).jsx
Copied:		Tych%20Panel%20-%20New%20row%20(top).jsx
Created Folder:	C:\Program Files\Adobe\Adobe Photoshop CC 2015\Presets\Scripts\Tych Panel\Tych Panel Only
Copied:		actions.jsx
Copied:		artlayers.jsx
Copied:		bridge.jsx
Copied:		colorpicker.jsx
Copied:		constants.jsx
Copied:		Delegate.jsx
Copied:		helpers.jsx
Copied:		ImageItem.jsx
Copied:		ImageList.jsx
Copied:		Json.jsx
Copied:		layerMaskLib.9.jsx
Copied:		layersets.jsx
Copied:		PSSettings.jsx
Copied:		reorder.jsx
Copied:		settings.jsx
Copied:		Tych.jsx
Copied:		TychTransformations.jsx

Ended copying files for SCRIPT.

MAC_PLUGIN - Nothing to install


WIN_PLUGIN - Nothing to install


EXTRA - Nothing to install

**Comment by reimund** [comment]
There's a new version, 2.3.6 with an updated installer script. Not sure it solves your issue but it's worth a try.
