### ISSUE TITLE
Tychpanel options button crashing Photoshop cc2015

### ISSUE THREAD

**Issue by markhadden69** [reimund/Tych-Panel#18]
HI 

I installed the updated tychpanel for photoshop cc15.  The panel works except when i try to change the option like the spacing between images etc.  As soon as i press the options button photoshop crashes immediately.  Any ideas?  Help much appreciated.  I love this panel and used it with cc14 seamlessly. Thanks
mark

**Comment by reimund** [comment]
http://feedback.photoshop.com/photoshop_family/topics/ps-cc2015-win7-crashes-instantly-when-extension-uses-script-ui

**Comment by markhadden69** [comment]
I figured a workaround for this.  By accident.. When i press the options
button on the panel first it crashes Photoshop.  But if i access the tools
from the scripts drop down it fixes it and then the button on the panel can
be used again.

Weird but it works. thanks

Mark
