### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by m1mx** [reimund/Tych-Panel#19]
I'm trying to install  Tych-Panel on PS CC 2014 on Mac 10.10.3

When I run the package-html (from desktop) I get the following...

Last login: Wed Jul 29 07:21:43 on ttys000
You have new mail.
Macintosh:~ michaelredding$ /Users/michaelredding/Desktop/Tych-Panel-master/package-html ; exit;
mkdir: dist: No such file or directory
find: ./Library/Saved Application State/com.adobe.dmp.contentviewer.installer.savedState: Permission denied
find: ./Library/Saved Application State/com.adobe.flashplayer.installmanager.savedState: Permission denied
/Users/michaelredding/Desktop/Tych-Panel-master/package-html:30: command not found: zxpsigncmd
logout

[Process completed]

Am I doing something wrong?

**Comment by reimund** [comment]
You need to install zxpsigncmd, create a certificate and probably manually create the dist directory (from your output it looks like I missed adding it to the script). The package-html script expects a second parameter which is the p12 password.

For more information check out these two
http://www.davidebarranca.com/2014/05/html-panels-tips-10-packaging-zxp-installers/ https://github.com/Adobe-CEP/CEP-Resources/wiki/CEP-6-HTML-Extension-Cookbook-for-CC-2015
