### ISSUE TITLE
Windows/Extensions greyed out,

### ISSUE THREAD

**Issue by BenAZPhoto** [reimund/Tych-Panel#20]
Installed using CC2015 installer, and the only place I find access to Tych is in File/Scripts/Tych Column L or Column R and Row Top

Multiple uninstalls, restart I get a dialog box which says Install successful need to restart application.

PSCC 2015.1.02

OSX 10.10.4 16GB MD314LLA

Thanks

**Comment by reimund** [comment]
Try new CC 2015.5 installer.
