### ISSUE TITLE
Incompatible with CC 2018?

### ISSUE THREAD

**Issue by silentdragoon** [reimund/Tych-Panel#21]
I had Tych-Panel installed on CC 2017 with no issues, but it disappeared when installing CC 2018. I went through the installation procedure again and it apparently finished without issue, but I don't see Tych as an option in the Window -> Extensions menu. Any ideas?

**Comment by capricorn8** [comment]
Same problem here.

**Comment by silentdragoon** [comment]
The workaround I'm using for now is assigning Tych Left and Tych Right to keyboard shortcuts, rather than needing to find them in File -> Scripts. I don't use the layer keyboard shortcuts very often, so I've rebound Ctrl + E and Ctrl + Shift + E to concatenate images to the right and to the left, respectively.
![2017-10-30 11_29_08-keyboard shortcuts and menus](https://user-images.githubusercontent.com/400279/32168701-921a727a-bd65-11e7-8fb4-a7a514acd11e.png)

**Comment by capricorn8** [comment]
Problem solved with latest update 2.5.0
