### ISSUE TITLE
Can't install on PS CC 20.0.4

### ISSUE THREAD

**Issue by chrabo** [reimund/Tych-Panel#23]
Hey, I've followed installation instructions to the letter but still can't run Tych Panel on Photoshop CC 2019 (20.0.4). Do I have to wait for an update or something? Thanks

**Comment by capricorn8** [comment]
Same here. No way to get the panel installed on PS 2020. I'm running PS as admin, the target folder is even existing (created manually), but the installer keeps coming back with "Could not create folder" messages. Would be really great to have this fixed to keep this beautiful extension alive! Thank you

**Comment by silentdragoon** [comment]
Same issue here - none of the buttons work and re-running the installation results in the message that the folder should be created manually or Photoshop should be run as an administrator (both of which I've done). I love this plugin and would be happy to sponsor a fix to this issue!

**Comment by silentdragoon** [comment]
I fixed the issue by copying the contents of the Tych Panel folder from my previous version of Photoshop (C:/Program Files/Adobe/Adobe Photoshop 2019/Presets/Scripts/Tych Panel) to the new version (C:/Program Files/Adobe/Adobe Photoshop 2020/Presets/Scripts/Tych Panel). Hope this helps someone else!

**Comment by beyondskyway** [comment]
> I fixed the issue by copying the contents of the Tych Panel folder from my previous version of Photoshop (C:/Program Files/Adobe/Adobe Photoshop 2019/Presets/Scripts/Tych Panel) to the new version (C:/Program Files/Adobe/Adobe Photoshop 2020/Presets/Scripts/Tych Panel). Hope this helps someone else!

macos 10.14.4 ps 21.0.3 can't work.

**Comment by reimund** [comment]
I've updated the package to use the latest CEP version eg compatibility with CC 2019/2020.

The latest download link is on https://github.com/reimund/Tych-Panel.

**Comment by capricorn8** [comment]
Hej Reimund,

 

When I click the download link on github, it gets me tychpanel-2.5.0.zip, not 2.6.0  !??

 

Regards

Karsten

**Comment by reimund** [comment]
Thanks for letting me know. The mistake has now been corrected!

**Comment by Brunodeto** [comment]
Hello,
Congratulation this program.
I have installed it in photoshop CS5 but can't get it to work.

 If using photoshop , tych panel appears on the screen but remains inactive. What should be the fix for the instalation.

Thank you.
Bruno
